FROM darkestpriest/aws-sam-cli:0.2

LABEL maintainer="Manuel Perez <darkpriestrelative@gmail.com>"
LABEL name="darkestpriest/lambda-function-runtime"

USER root
COPY ".aws-sam/" "/home/linuxbrew/.aws-sam/"

EXPOSE 3000